import { defaultValues } from "@/configs"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import { makeServer } from "../mocks"
import "./globals.css"
import { MirageSetup } from "./mirage-setup"

if (process.env.NODE_ENV === "development" && defaultValues.isMocksApiEnable) {
  makeServer({ environment: "development" })
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MirageSetup />
        {children}
      </body>
    </html>
  )
}
