export enum Status {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BANNED = 'BANNED',
  TRUSTED = 'TRUSTED',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',

  UNVERIFIED = 'UNVERIFIED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED',
  SUSPENDED = 'SUSPENDED',

  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  SCHEDULED = 'SCHEDULED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  UNDER_REVISION = 'UNDER_REVISION',
  APPROVED = 'APPROVED',
}

export default Status;
